### ISSUE TITLE
win10 NtClose in x86

### ISSUE THREAD

**Issue by thegfw** [j00ru/windows-syscalls#1]
MOV EAX,3000F
 MOV EDX,ntdll.77493380
CALL EDX
RETN 4

**Comment by thegfw** [comment]
wow64 and x64

**Comment by KNSoft** [comment]
@thegfw system service index is 0xF, that right. It's works well if you change it to "mov eax,0Fh".

**Comment by j00ru** [comment]
@thegfw In the wow64 version of ntdll.dll, the upper 16 bits of the syscall ID encode information about the syscall's arguments, so that they can be correctly converted to how the 64-bit kernel expects them.

More specifically, the value is used by `wow64cpu!TurboDispatchJumpAddressStart` to choose the dispatch function from the `wow64cpu!TurboThunkDispatch` list:

```
00000000`77bb4620 0000000077bb1908 wow64cpu!ServiceNoTurbo
00000000`77bb4628 0000000077bb1e06 wow64cpu!Thunk0Arg
00000000`77bb4630 0000000077bb1ca8 wow64cpu!Thunk0ArgReloadState
00000000`77bb4638 0000000077bb1db6 wow64cpu!Thunk1ArgSp
00000000`77bb4640 0000000077bb1dc7 wow64cpu!Thunk1ArgNSp
[...]
```

In this case, `wow64cpu!Thunk1ArgSp` (at index 3) is used to convert the single parameter of `NtClose`, and then call into kernel-mode. So, the actual system call ID is still 0xF.
